# Generated by Django 5.2.5 on 2025-08-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_task_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['completed', '-priority', 'due_date', '-created_at']},
        ),
        migrations.AddField(
            model_name='task',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
